apiVersion: v1
data:
  {{- with .Values.database }}
  database-name: {{ .dbname | default "sampledb" | b64enc}}
  database-password: {{ .password  | default (randAlphaNum 8) | b64enc }}
  database-user: {{ .username | default (randAlpha 8) | b64enc }}
  {{- end }}
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
  name: {{ $.Values.name }}
type: Opaque
