apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: {{ $.Values.name }}
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
    deployment: {{ $.Values.name }}
  sessionAffinity: None
  {{- if $.Values.expose }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
